source 'https://rubygems.org'
git_source(:gitlab) { |repo_name| "https://gitlab.com/#{repo_name}.git" }

gem 'rails', '6.0.6.1'
# gem 'rails', '~> 5.0'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3', '~> 1.4'
# gem 'sqlite3', '~> 1.3.6'
gem 'active_list', path: '../..'

gem 'sprockets', '< 4'

gem 'onoma', gitlab: 'ekylibre/onoma'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails'
  gem 'coffee-rails'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  gem 'mini_racer'

  gem 'uglifier'
end

gem 'jquery-rails'

gem 'minitest', "~> 5.20.0", group: :test
gem 'minitest-reporters', '~> 1.4', group: :test

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
