stages:
  - test

.test_base: &tpl_base
  before_script:
    - gem install bundler
    - bundle config set jobs "$(nproc)"
    - bundle install
  script:
    - (cd test/dummy && bundle install && bundle exec rake db:drop db:create db:migrate db:seed RAILS_ENV=test)
    - bin/rake test

test_2_6:
  <<: *tpl_base
  image: registry.gitlab.com/ekylibre/docker-base-images/ruby2.6:1
